version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_reviews
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default

  app:
    build: .
    container_name: java-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  pgdata:

networks:
  backend:
