apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: default
  labels:
    app: postgres
    tier: backend
  annotations:
    description: "PostgreSQL credentials"
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: YWRtaW4=